# Generated by Django 5.0.6 on 2024-05-27 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, null=True)),
                ('phoneNumber', models.CharField(blank=True, db_index=True, max_length=30, null=True)),
                ('linkedId', models.IntegerField(null=True)),
                ('linkPrecedence', models.CharField(choices=[('primary', 'primary'), ('secondary', 'secondary')], default='primary', max_length=256)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('deletedAt', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
